# Generated by Django 3.2.9 on 2022-07-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220726_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
