# Generated by Django 4.0.6 on 2022-07-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_root_app', '0002_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_root_app.templates'),
        ),
    ]
