# Generated by Django 4.0.6 on 2022-07-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_root_app', '0003_remove_templates_user_user_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=200)),
                ('autoload', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(to='cms_root_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now_add=True)),
                ('Template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_pages', to='cms_root_app.templates')),
            ],
        ),
        migrations.CreateModel(
            name='page_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('page_created_from', models.ManyToManyField(to='cms_root_app.pages')),
            ],
        ),
    ]
