# Generated by Django 4.0.6 on 2022-07-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_root_app', '0004_settings_pages_page_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pages',
            new_name='page',
        ),
        migrations.RenameModel(
            old_name='settings',
            new_name='setting',
        ),
        migrations.RenameModel(
            old_name='templates',
            new_name='template',
        ),
    ]
