# Generated by Django 4.0.6 on 2022-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_root_app', '0005_rename_pages_page_rename_settings_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
