# Generated by Django 4.0.6 on 2022-07-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_root_app', '0006_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
